### ISSUE TITLE
glTexImage2D invalid value (crash)

### ISSUE THREAD

**Issue by bshanks** [paoletto/PythonPhotoSphere#3]
Trying to view the attached file, a photosphere taken with the built-in camera app on an Android Nexus 5x (Android 6.0 = Android Marshmallow), causes the following error:

![2015-11-24 17 02 04](https://cloud.githubusercontent.com/assets/586225/11540546/33cf991a-98e2-11e5-8534-fa4f87242e5b.jpg)

```
Traceback (most recent call last):
  File "PhotoSphere.py", line 197, in <module>
    main()
  File "PhotoSphere.py", line 134, in main
    Initialize (640, 480, fileUrl)
  File "/home/username/Downloads/PhotoSphereBundle/App/PhotoSphereRenderer.py", line 153, in Initialize
    GL_RGB, GL_UNSIGNED_BYTE, g_texData
  File "/usr/lib/python2.7/dist-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/usr/lib/python2.7/dist-packages/OpenGL/wrapper.py", line 792, in wrapperCall
    raise err
OpenGL.error.GLError: GLError(
        err = 1281,
        description = 'invalid value',
        baseOperation = glTexImage2D,
        pyArgs = (
                GL_TEXTURE_2D,
                0,
                GL_RGB,
                8704,
                5657,
                0,
                GL_RGB,
                GL_UNSIGNED_BYTE,
                array([0, 0, 0, ..., 0, 0, 0], dtype=...,
        ),
        cArgs = (
                GL_TEXTURE_2D,
                0,
                GL_RGB,
                8704,
                5657,
                0,
                GL_RGB,
                GL_UNSIGNED_BYTE,
                array([0, 0, 0, ..., 0, 0, 0], dtype=...,
        ),
        cArguments = (
                GL_TEXTURE_2D,
                0,
                GL_RGB,
                8704,
                5657,
                0,
                GL_RGB,
                GL_UNSIGNED_BYTE,
                array([0, 0, 0, ..., 0, 0, 0], dtype=...,
        )
)
```

**Comment by bshanks** [comment]
Fork https://github.com/andree182/PythonPhotoSphere seems to be able to handle this file without crashing.
